Remove deprecated macro in newer json-c
:Release Notes:
Newer json-c doesn't support is_error macro

:Detailed Notes:
Fix following
error: 'is_error' was not declared in this scope

:Testing Performed:

:QA Notes:

:Issues Addressed:

Change-Id: I475ea9a14cca21488386b9afaa579007e3d93d62
Reviewed-on: http://gpro.lgsvl.com/211711
Reviewed-by: Kyungjik Min <dp.min@lge.com>
Tested-by: Kyungjik Min <dp.min@lge.com>