CMakeLists.txt: install libtatlas.so in regular libdir instead of /usr/local/atlas/lib
:Release Notes:
With newer meta-updater this only file in /usr/local breaks
do_image_ostree.

:Detailed Notes:
With:
https://github.com/advancedtelematic/meta-updater/commit/bc6c9f098442a2c0bf4a7a40ba50c9ee5fe40cc1#diff-e2abc18e16bca9de6396cc6ab17ac27f
it fails with:
WARNING: webos-image-devel-1.0-r2 do_image: Android repo tool not found; manifest not copied.
WARNING: webos-image-devel-1.0-r2 do_image_ostree: Data in /opt directory is not preserved by OSTree. Consider moving it under /usr
WARNING: webos-image-devel-1.0-r2 do_image_ostree: Data in /mnt directory is not preserved by OSTree. Consider moving it under /usr
ERROR: webos-image-devel-1.0-r2 do_image_ostree: Data in /usr/local directory is not preserved by OSTree.
ERROR: webos-image-devel-1.0-r2 do_image_ostree: Function failed: do_image_ostree (log file is located at /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image-devel/1.0-r2/temp/log.do_image_ostree.16291)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image-devel/1.0-r2/temp/log.do_image_ostree.16291

:Testing Performed:

:QA Notes:

:Issues Addressed:

Change-Id: I6a6619d92664c5ab104ece976dc7cbc0fa1d2d10